# version: '3.7'

# services:
#   db:
#     image: mysql:latest
#     container_name: mysql-db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: task_management
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     volumes:
#       - ./mysql_data:/var/lib/mysql
#     ports:
#       - "3306:3306"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     restart: always
#     depends_on:
#       - db
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: password
#     ports:
#       - "8080:80"

# ==========================

version: '3.7'

services:


  db:
    image: mysql:latest
    platform: linux/amd64
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
    - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
    - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: task_management
      TZ: Asia/Bangkok
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    restart: always
    networks:
    - app-network


networks:
    app-network :
      driver: bridge